package com.apps.bellatrix.booketh;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.RecyclerView;
import android.support.v7.widget.StaggeredGridLayoutManager;
import android.widget.GridView;

import com.apps.bellatrix.booketh.Adapters.BookPageAdapter;

import java.util.ArrayList;

public class TrendingBooksActivity extends AppCompatActivity {

    RecyclerView recViewTrending;
    ArrayList <Book> books = new ArrayList<>();


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_trending_books);

        recViewTrending = findViewById(R.id.recViewTrending);

        books.add(new Book("Wicked Wide Wonderful", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 2, true, R.drawable.b));
        books.add(new Book("Dialogue Concerning The Imminent Apocalypse", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, false, R.drawable.c));
        books.add(new Book("Dialogue Concerning The Imminent Apocalypse", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, false, R.drawable.c));
        books.add(new Book("Dialogue Concerning The Imminent Apocalypse", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, false, R.drawable.c));
        books.add(new Book("Wicked Wide Wonderful", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, true, R.drawable.b));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, false, R.drawable.d));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, true, R.drawable.d));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 2, true, R.drawable.d));
        books.add(new Book("Wicked Wide Wonderful", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, false, R.drawable.b));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, false, R.drawable.d));
        books.add(new Book("Wicked Wide Wonderful", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, false, R.drawable.b));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, true, R.drawable.d));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, false, R.drawable.d));
        books.add(new Book("The Omens of a Crown", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, true, R.drawable.d));
        books.add(new Book("Wicked Wide Wonderful", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 3, false, R.drawable.b));
        books.add(new Book("Dialogue Concerning The Imminent Apocalypse", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, true, R.drawable.c));
        books.add(new Book("Dialogue Concerning The Imminent Apocalypse", "Book tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi convallis eros quis risus condimentum condimentum. Vestibulum id venenatis ante. Cras vel porta dolor. Pellentesque blandit nulla iaculis dictum volutpat. Vivamus at tortor ut turpis accumsan auctor ut id nisl. Nunc sagittis sed neque in fringilla. Fusce eu felis ut turpis tempor accumsan nec at enim.", 1, true, R.drawable.c));

        BookPageAdapter adapter = new BookPageAdapter(books, this);
//        recViewTrending.setLayoutManager(new StaggeredGridLayoutManager(5, StaggeredGridLayoutManager.HORIZONTAL));

        StaggeredGridLayoutManager layoutManager = new StaggeredGridLayoutManager(3,StaggeredGridLayoutManager.VERTICAL);
        layoutManager.setGapStrategy(StaggeredGridLayoutManager.GAP_HANDLING_NONE);
        recViewTrending.setLayoutManager(layoutManager);
        recViewTrending.setHasFixedSize(true);
        recViewTrending.setAdapter(adapter);
    }
}
